# fly.toml file generated for empty-fog-8397 on 2022-12-30T13:51:15-05:00

app = "empty-fog-8397"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []